### ISSUE TITLE
Generate more standard-expected documentations

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#2339]
Feedback from some workshop is that we should try and have closer to ecosystem documentations. One example was NodeJS API which has no doc, and calls bindings directly, making people have to read the C header. That looks to be un-natural to them and a blocking point.

- [x] Generate Java doc #2362
- [x] Generate NodeJS doc #2362
- [x] Generate Python doc #2362
- [x] Generate C doc #2362
