### ISSUE TITLE
Publishing training Dockerfile

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#3057]
- [x] Decouple training from building #3056
 - [x] Add repo-level support for Docker Hub automated builds #3117 
 - [x] Create repositories under the mozilla repo
 - [x] Setup CircleCI-based build & deploy to Docker Hub #3157

**Comment by DanBmh** [comment]
With the current `Dockerfile.train` I had some issues with cudnn: `No OpKernel was registered to support Op 'CudnnRNNCanonicalToParams'`

I could solve it with the following steps:
- Use `FROM nvcr.io/nvidia/tensorflow:20.03-tf1-py3` as new base image
- Remove the three `venv` commands
- Remove the `--force-reinstall` flag in DeepSpeech pip installation

I'm not quite sure if you need all of them, but now it's possible train from an existing checkpoint again. Maybe i find some time  in the next days to find out which statement was important.

**Comment by reuben** [comment]
Weird, the 2nd and 3rd steps should not be related to CUDA/cuDNN at all. Are you sure it wasn't just the new base image that solved it?

**Comment by DanBmh** [comment]
No, i'm pretty sure it wasn't just this. I think this is related to the reinstallation of tensorflow.

**Comment by reuben** [comment]
Ah, that makes sense, the base image already comes with TensorFlow installed and it has some magic options.

**Comment by lissyx** [comment]
Can we avoid hijacking issues?

**Comment by use-to** [comment]
@lissyx Maybe you can better use the github webhooks instead of the scriptworker to link to github on the docker hub page. Also, the automatic builds of docker hub could speed up the pipeline.

**Comment by use-to** [comment]
@lissyx There is already an [existing docker hub account by mozilla](https://hub.docker.com/u/mozilla). It should be better to request access for that organization instead of creating a new one.

**Comment by lissyx** [comment]
> @lissyx Maybe you can better use the github webhooks instead of the scriptworker to link to github on the docker hub page. Also, the automatic builds of docker hub could speed up the pipeline.

There's a reason we use `scriptWorker`, maintaining two different CI / CD pipeline will be a burden.

**Comment by lissyx** [comment]
>     * [x]  Decouple training from building #3056
> 
>     * [ ]  Create docker hub account
> 
>     * [ ]  Add scriptworker upload ability to docker hub

So the situation is complicated:
 - we might be able to push from scriptworker using https://pypi.org/project/dockertarpush/
 - this code depends on docker image spec v1.1
 - current docker-in-docker service on taskcluster is stuck to docker v1.6, with API v1.18 https://github.com/taskcluster/dind-service/blob/master/Dockerfile#L6
 - so the `docker save` command we issue does produce v1.0 docker image spec
 - kaniko requires being executed from a docker image, but this fails with weird "HostConfig.NetworkMode" errors
 - trying to build kaniko + run it (ubuntu 20.04), it fails fetching some debian packages when building the image (?)

**Comment by lissyx** [comment]
Ok, Docker Hub Automated builds can support `hooks/`, so we might be able to rely on that for push-to-tag on releases.

**Comment by lissyx** [comment]
![Screenshot_2020-07-02 Docker Hub](https://user-images.githubusercontent.com/1645737/86388868-c46f5100-bc95-11ea-94b2-34d1c92cce2a.png)

**Comment by lissyx** [comment]
Still waiting on the people who are supposed to be in charge of the mozilla org on Docker Hub.

**Comment by lissyx** [comment]
So, #3157 merged, new alpha tagged:
 - master just built and deployed as `latest` on https://hub.docker.com/r/mozilla/deepspeech-train/tags
 - current master (after some new merge) building and will deploy within minutes
 - v0.9.0-alpha.3 tag building and will deploy within minutes
 - r0.8 branch PR merge still running on TaskCluster, but once it is merged it should produce docker image on Docker Hub

**Comment by lissyx** [comment]
> r0.8 branch PR merge still running on TaskCluster, but once it is merged it should produce docker image on Docker Hub

It should be good but there are issues on both Github and CircleCI, so nothing is starting for now, and I can't be sure it's all okay.
